{% set version = "0.4" %}

package:
  name: climlab-rrtmg
  version: {{ version }}

source:
  url: https://github.com/climlab/climlab-rrtmg/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4aae325ec6c93ccafff1695dc23036ea14e3f389dd1a502488865359e0e3c7cc

build:
  skip: true  # [win]  
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - ninja
    - pkg-config
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - meson-python
    - python
    - python-build
    - pip
    - numpy
    - packaging >=20.0
  run:
    - python
    - numpy

test:
  requires:
    - pytest
  imports:
    - climlab_rrtmg.rrtmg_lw
    - climlab_rrtmg.rrtmg_sw
  commands:
    - pytest -v --pyargs climlab_rrtmg

about:
  home: https://github.com/climlab/climlab-rrtmg
  summary: 'Standalone Python wrapper for the RRTMG radiation modules'
  description: |
    climlab-rrtmg makes the RRTMG_LW and RRTMG_SW radiation codes callable
    from Python by wrapping using f2py. This is a lightweight wrapper that
    emulates the Fortran interface as closely as possible. The primary use case
    is to drive the RRTMG radiation processes in climlab, but it can be used as
    a standalone driver if you are familiar with the RRTMG Fortran interface.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/climlab/climlab-rrtmg

extra:
  recipe-maintainers:
    - brian-rose
