{% set version = "0.3" %}

package:
  name: climlab-rrtmg
  version: {{ version }}

source:
  url: https://github.com/climlab/climlab-rrtmg/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5e9fb4b7da2efb1eefe74b61060998b9e41948ad3a72f0053f748df208bf6079

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py>311]
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}
  host:
    - libpython  # [win]
    - python
    - setuptools <60
    - pip
    - numpy
  run:
    - python
    - numpy <2

test:
  requires:
    - pytest
  imports:
    - climlab_rrtmg.rrtmg_lw
    - climlab_rrtmg.rrtmg_sw
  commands:
    - pytest -v --pyargs climlab_rrtmg

about:
  home: https://github.com/climlab/climlab-rrtmg
  summary: 'Standalone Python wrapper for the RRTMG radiation modules'
  description: |
    climlab-rrtmg makes the RRTMG_LW and RRTMG_SW radiation codes callable
    from Python by wrapping using f2py. This is a lightweight wrapper that
    emulates the Fortran interface as closely as possible. The primary use case
    is to drive the RRTMG radiation processes in climlab, but it can be used as
    a standalone driver if you are familiar with the RRTMG Fortran interface.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/climlab/climlab-rrtmg

extra:
  recipe-maintainers:
    - brian-rose
